### ISSUE TITLE
Feil signatur på AsicE

### ISSUE THREAD

**Issue by iko3** [difi/sikker-digital-post-klient-java#71] opened 2017-04-04 11:07 UTC
We are no longer able to send messages due to "Feil signatur på AsicE" error. 

Message gets sent successfully 
`sikkerDigitalPostKlient.send(forsendelse);`
but when we try to retrieve the receipt 
```
KvitteringForespoersel kvitteringForespoersel = KvitteringForespoersel.builder(Prioritet.NORMAL).mpcId("XXX").build();
            ForretningsKvittering forretningsKvittering = sikkerDigitalPostKlient.hentKvittering(kvitteringForespoersel);
```
we get an error that the message hasn't been delivered:

`Feil{konversasjonsId=XXXXXX, feiltype=KLIENT, detaljer='Feil signatur på AsicE'}`

What might be the cause of this problem? This is in production environment.

**Comment by rocketfarmsteinar** [comment] 2017-04-04 11:09
Hi

We'll investigate this and get back to you.

**Comment by aberner** [comment] 2017-04-04 11:29
@iko3 
could you please give us the conversationId used?

**Comment by iko3** [comment] 2017-04-04 11:31
For example, this one 96d7234a-5696-4c12-b0fd-eff80e323084

**Comment by rocketfarmsteinar** [comment] 2017-04-04 11:50
@iko3 This is most likely a configuration problem.

If you contact idporten@difi.no they will help you investigate what the actual problem is.

We'll close this issue for now, but don't hesitate to reopen if it turns out that the problem is in the client library.

**Closed by rocketfarmsteinar** 2017-04-04 11:50 UTC
